services:
  - type: web
    name: nasa-data-explorer-backend
    env: node
    plan: free
    buildCommand: cd backend && npm ci --include=dev && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NASA_API_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /health 