services:
  - type: web
    name: nasa-data-explorer-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NASA_API_KEY
        sync: false
      - key: NASA_API_BASE_URL
        value: https://api.nasa.gov
      - key: CORS_ORIGIN
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: CACHE_ENABLED
        value: true
      - key: CACHE_DEFAULT_TTL
        value: 300000
      - key: LOG_LEVEL
        value: info
      - key: LOG_REQUESTS
        value: true
    healthCheckPath: /health 