services:
  - type: web
    name: nasa-data-explorer-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: fn26y6c3iJUKPyilf8099ggmpCZQldWP8xTscwhw
        sync: false
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /health 